---
- name: Sample playbook
  hosts: all
  vars:
    ansible_user: "ec2-user"
    ansible_ssh_private_key_file: "~/.ssh/ec2sample"
  tasks:
    - name: Update all packages
      become: yes
      dnf:
        name: "*"
        state: latest
